### ISSUE TITLE
Format source files with shfmt

### ISSUE THREAD

**Issue by SuperSandro2000** [brujoand/sbp#102]
**Describe the bug**
The source code is using a lot of quotes and whitespaces where it isn't necessary. I am always formatting my changes with shfmt and get a pretty big diff in this project.

**To Reproduce**
1. run ``shfmt -ci -i 2 -s -w $file``
2. run ``git diff``
3. See diff

**Expected behavior**
I would appreciate it if the diff wasn't as big so that I can easily format my changes without generating a giant diff.

The question is: do you want this? Should I format all files with shfmt or not?

**Additional context**
I am currently working on [gitstatus](https://github.com/romkatv/gitstatus) support which requires a few changes in the git segment where I noticed that.

**Comment by brujoand** [comment]
Yeah, this was about time. Fixed by #130
