### ISSUE TITLE
What font needed to render -> on the prompt?

### ISSUE THREAD

**Issue by thepenguinthatwants** [brujoand/sbp#111]
Hi,
I've reinstalled my arch machine and was wondering how to get the -> to shown?
Its now having a square at it, but I already installed powerline font, so not sur why its still like that.

The problem occurs with alacritty and st terminal.

**Comment by spamegg1** [comment]
@thepenguinthatwants You might have to change your terminal font to the Powerline font. Can you show your terminal settings, which font you installed, your `sbp` settings (something like `/home/yourusername/.config/sbp/settings.conf`) and maybe some screenshots?

**Comment by thepenguinthatwants** [comment]
Hi my configs looks like this

```
SBP_THEME_COLOR='default-256'
SBP_THEME_LAYOUT='plain'
SBP_HOOKS=('alert')
if [[ "$COLUMNS" -le 120 ]]; then
  # Let's adjust to the smaller screen
  SBP_THEME_LAYOUT='lines'
  SBP_SEGMENTS_LEFT=('path' 'python_env' 'git' 'command')
else
  SBP_SEGMENTS_LEFT=('host' 'path' 'python_env' 'k8s' 'git' 'nix')
  SBP_SEGMENTS_RIGHT=()
  SBP_SEGMENTS_LINE_TWO=('prompt_ready')
fi

SEGMENTS_K8S_DEFAULT_USER="$USER"
SEGMENTS_K8S_HIDE_CLUSTER=0
SEGMENTS_LOAD_THRESHOLD=50
SEGMENTS_LOAD_THRESHOLD_HIGH=80
SEGMENTS_RESCUETIME_REFRESH_RATE=600
SEGMENTS_TIMESTAMP_FORMAT="%H:%M:%S"
SEGMENTS_WTTR_LOCATION='Oslo'
SEGMENTS_WTTR_FORMAT='%p;%t;%w'
```

And the prompt looks like this
 ninja ~/.config/sbp ?3 master
 ➜

**Comment by thepenguinthatwants** [comment]
![image](https://user-images.githubusercontent.com/46752217/117565624-dd693f80-b0ba-11eb-981a-53cd8706ef64.png)

**Comment by thepenguinthatwants** [comment]
When I use
fc-list |less
I can see

`/home/ninja/.local/share/fonts/Inconsolata for Powerline.otf: Inconsolata for Powerline:style=Medium`

Also this problem occurs in alacritty and ST.

**Comment by spamegg1** [comment]
@thepenguinthatwants Change `SBP_THEME_LAYOUT='plain'` to `SBP_THEME_LAYOUT='powerline'` and save the file, restart your terminal. What happens?

**Comment by thepenguinthatwants** [comment]
Ah yeh sorry the powerline does work, but what I meant is the -> sign is a square.

**Comment by thepenguinthatwants** [comment]
The `prompt ready` doesnt render right.

**Comment by spamegg1** [comment]
What does `echo $COLUMNS` say?
Maybe try a different font from here: https://github.com/powerline/fonts

**Comment by thepenguinthatwants** [comment]
It says
169

**Comment by thepenguinthatwants** [comment]
Adding or changing fonts doesn't seem to  help.

**Comment by spamegg1** [comment]
Try looking into any "Compatibility" type settings in your terminal, check "Encodings" and so on.

**Comment by thepenguinthatwants** [comment]
I don't seem to be able to find whats wrong.
All the other stuff seems to render fine even on my terminal
Is there a way I can override the prompt_ready default -> into something else?

**Comment by thepenguinthatwants** [comment]
Seems like its the , SEGMENTS_PROMPT_READY_ICON

**Comment by spamegg1** [comment]
I was able to edit the file in my install location `/home/spamegg/opt/sbp/src/layouts/powerline.bash`
I changed
```
SEGMENTS_PROMPT_READY_ICON=${LAYOUTS_POWERLINE_PROMPT_READY_ICON:-'➜'}
```
to
```
SEGMENTS_PROMPT_READY_ICON=${LAYOUTS_POWERLINE_PROMPT_READY_ICON:-'***'}
```
and now it displays `***` instead of `➜`

**Comment by spamegg1** [comment]
Try some other terminals as well. My best guess is that it seems like those two terminals (or maybe your system?) have trouble rendering certain Unicode characters correctly, like ➜ which is U+279C https://unicode-table.com/en/279C/

When you copy-pasted your prompt here, ➜ rendered correctly HERE. So the correct character is there but does not render.

I'm using `gnome-terminal` and ➜ renders fine with any font.

**Comment by infogulch** [comment]
For reference you can set `LAYOUTS_PLAIN_PROMPT_READY_ICON='***'` with `spb edit config` instead of editing `plain.bash`.

It seems like the layout file (e.g. `plain.bash`) is run after user config, which overrides the user setting `SEGMENTS_PROMPT_READY_ICON` in user config directly. Personally I would expect user config to have a higher precedence than layouts.
