### ISSUE TITLE
Time Settings

### ISSUE THREAD

**Issue by Phidelux** [brujoand/sbp#12]
There seems to be a problem with the merge of the settings pull request for the time settings. The variable was introduced in the settings and in the segment file but never used. However, a look in my repo showed that the time segment is implemented correctly. As my laptop broke today, I cannot look into it. Sry.

**Comment by brujoand** [comment]
Yeah, this was due to a type in the default variable setting of the time format. I pushed a fix right after merging your PR so should be fixed.

**Comment by Phidelux** [comment]
The error still persists. The variable is never used.

**Comment by brujoand** [comment]
I'm sorry, could you be a bit more specific? What is the error you are seeing?

**Comment by Phidelux** [comment]
Sorry, the variable containing the time format is set properly, but never used. The following line 

`timestamp_value=$(date +%H:%M:%S)`

has to be changed to

`timestamp_value=$(date +"$_sbp_timestamp_format")`.

This should work properly. However, in my fork the code is correct, but wasn't merged correctly.

**Comment by brujoand** [comment]
Oh yeah. This should do it #21
