### ISSUE TITLE
Use git-prompt.sh for git.bash

### ISSUE THREAD

**Issue by yan-ming** [brujoand/sbp#13]
Git has its own prompt helper, there's no need to do `git rev-parse` manually. `__git_ps1` should do a better job.

https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh

**Comment by brujoand** [comment]
Good point. I did use __git_ps1 initially but found that it wasn't always available on the systems I was working on. It's probably a good idea to change sbp's default git segment to use __git_ps1 and deprecate the current git segment calculation to a legacy version. It's probably both faster and more robust.

**Comment by yan-ming** [comment]
This should work on the both system I have. :)

```bash
# Archlinux
if [ -d /usr/share/git/completion/ ] ; then
  source /usr/share/git/completion/git-prompt.sh
fi

# OS X
if [ -d /usr/local/etc/bash_completion.d/ ] ; then
  source /usr/local/etc/bash_completion.d/git-prompt.sh
fi
```

**Comment by dflock** [comment]
You could make this a setting and do something like this in `git.bash`:

```bash
_sbp_git_prompt_location=${_sbp_git_promt_location:-'/usr/share/git/completion/'}

function _sbp_generate_git_segment() {
  if [ -f "$_sbp_git_prompt_location" ]; then
    source "$_sbp_git_prompt_location"
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWUPSTREAM=1
    GIT_PS1_DESCRIBE_STYLE="branch"
    GIT_PS1_SHOWUPSTREAM="auto git"
    git_value=$(__git_ps1 '%s')
  else
    [[ -n "$(git rev-parse --git-dir 2> /dev/null)" ]] || return 0
    local git_head git_state git_value
    git_head=$(sed -e 's,.*/\(.*\),\1,' <(git symbolic-ref HEAD 2>/dev/null || git rev-parse --short HEAD))
    git_state=" $(git status --porcelain | sed -Ee 's/^(.M|M.|.R|R.) .*/\*/' -e 's/^(.A|A.) .*/\+/' -e 's/^(.D|D.) .*/\-/' | grep -oE '^(\*|\+|\?|\-)' | sort -u | tr -d '\n')"
    git_value="${git_head}${git_state}"
  fi

  _sbp_segment_new_color_fg="$_sbp_git_color_fg"
  _sbp_segment_new_color_bg="$_sbp_git_color_bg"
  _sbp_segment_new_length="$(( ${#git_value} + 0 ))"
  _sbp_segment_new_value="${git_value} "
  _sbp_segment_new_create
}
```

then you can override the setting in your `~/.sbp` file:

```bash
_sbp_git_prompt_location='/home/duncan/.git-prompt.sh'
```

I've been playing with this and it works ok for me:

![image](https://cloud.githubusercontent.com/assets/47756/13761713/8edc4f0e-e9f7-11e5-864f-b5b1f6ffb337.png)

I would be nice to customize the chars it uses for indicating ahead, behind, etc.. but I haven't figured that out yet. The `git-prompt.sh` script is here and well commented: https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh

You could also make sbp settings for those `GIT_PS1_*` env var settings, obviously.

**Comment by dflock** [comment]
I have a branch where I'm working on this: https://github.com/dflock/sbp/tree/updated_git_segment

**Comment by brujoand** [comment]
I've let the segment use __git_ps1 if it's available now. Settings for the different characters would be very nice. :+1: 
Closing the issue as it's resolved.
