### ISSUE TITLE
Moving segments and configuration

### ISSUE THREAD

**Issue by Phidelux** [brujoand/sbp#17]
Maybe the configuration of sbp should be moved to ~/.config/sbp . The segments could be placed in ~/.config/sbp/segments and the config file is also moved there (eg. ~/.config/sbp/sbp.conf).

**Comment by dflock** [comment]
I like this idea - you'd have to change `helpers/imports.bash` to be dynamic to make this useful, I think (see here: https://github.com/brujoand/sbp/issues/14)

Probably it should import from the default `segments` folder, then also import from the user one in `~/.config/segments`, to allow you to override/add your own segments to the default ones?

**Comment by brujoand** [comment]
Yeah, using ~/.config/sbp seems to be the way to go. Putting user segments/hooks in the config folder while keeping the defaults also makes a lot of sense and it's also a good argument to get rid of the imports.bash. :+1:

**Comment by brujoand** [comment]
Implemented by #64
