### ISSUE TITLE
Multiple empty lines on long path

### ISSUE THREAD

**Issue by Phidelux** [brujoand/sbp#2]
If the path gets very long, the time gets moved to the next line or should get moved to the next line. Actually there are several lines between the username and the time part of the prompt.

**Comment by brujoand** [comment]
Yeah, this was on my todo list but slipped away from me. I'm thinking that there are two ways of solving this. Either set a max length for the path segment and replace intermediate folders with ... like so: 

```~/mycode/project/src/main/.../java```  

or even better, set each segments maximum length to (1/x)*y where x is the number of segments and y is the available length in total. It's probably a good idea to let each segment decide how to deal with little space. 

Should work in most cases i think.

**Comment by brujoand** [comment]
I've made a default setting for truncation length for the path now, so this should be fixed. Please reopen if not.

**Comment by Phidelux** [comment]
Works fine, thanks!
