### ISSUE TITLE
Extra width added at end of settings_segments_right

### ISSUE THREAD

**Issue by xHN35RQ** [brujoand/sbp#30]
I'm seeing an extra space plus an extra tab added to the end of `settings_segments_right`. I'm curious why this might be. I just noticed this start happening after the latest merge.

```
 last: 0m 0s  02:11:57  
```
Default sbp settings and empty .bashrc, Ubuntu 16.04 mate-terminal

**Comment by dflock** [comment]
I see this too, on current master. Not sure why this was closed.

**Comment by brujoand** [comment]
Let's reopen it. What version of bash are you on @dflock ?

**Comment by brujoand** [comment]
Does #36 help on this?

**Comment by dflock** [comment]
GNU bash, version 4.2.45(1)-release (x86_64-pc-linux-gnu)

**Comment by dflock** [comment]
Yes, I pulled up to latest master and it fixed the issue - thanks!
