### ISSUE TITLE
Error indicator no longer turns red for failed command

### ISSUE THREAD

**Issue by xHN35RQ** [brujoand/sbp#31]
Before the latest merge, typing `thiscommandwillfail` would turn the command segment red. Now nothing happens. Is there something I need to enable for this functionality? Thanks!

Default sbp settings and empty .bashrc, Ubuntu 16.04 mate-terminal

**Comment by brujoand** [comment]
Ah, thanks for reporting this. I hadn't noticed but, it turns out my major refactoring did break some things then.

**Comment by xHN35RQ** [comment]
Testing with latest merge of #32 shows no change. Indicator still not red.

**Comment by brujoand** [comment]
Hm, that's really odd. I'll have to have a look later, just arrived at work.

**Comment by xHN35RQ** [comment]
Ok no problem. thank you!

**Comment by brujoand** [comment]
Can you try to set your prompt command to append to history?
```
PROMPT_COMMAND="_sbp_set_prompt;history -a;"
```

I suspect this is related to using history as a source of truth for previous commands.

**Comment by xHN35RQ** [comment]
placing `PROMPT_COMMAND="_sbp_set_prompt;history -a;"` into my `.bashrc` doesn't do anything. Do I need to enable the `exit_code` segment?

**Comment by brujoand** [comment]
Did you figure this out?

**Comment by xHN35RQ** [comment]
No, I wasn't able to, and don't really have the time. :watch:

**Comment by dflock** [comment]
This is still not working for me - and adding `history -a` the `PROMPT_COMMAND` doesn't make any difference.

**Comment by brujoand** [comment]
Yeah I think this is directly related to #35. Reopening it.

**Comment by brujoand** [comment]
So #37 fixed this for me. Could you guys confirm?

**Comment by xHN35RQ** [comment]
I no longer use sbp. Sorry I can't be more helpful. :disappointed:

**Comment by dflock** [comment]
Yes, this is fixed on latest master, thanks!

**Comment by brujoand** [comment]
Great!
