### ISSUE TITLE
bash: script.sh: syntax error: operand expected (error token is "script.sh")

### ISSUE THREAD

**Issue by dflock** [brujoand/sbp#35]
I have this problem with the current master. After I run most bash scripts I get an error like the following:

```
bash: script.sh: syntax error: operand expected (error token is "script.sh")
```

I have  reduced test case for this issue. This tiny bash script:

```
echo 'test'
```

when saved an run, will output this:

```
 duncan  ~  tmp                                                                                                                  last: 0m 0s  13:23:10  
 ➜ ./sbp_error_test_3.sh 
test
bash: ./sbp_error_test_3.sh: syntax error: operand expected (error token is "./sbp_error_test_3.sh")
```

**Comment by brujoand** [comment]
Yeah, I've just discovered this also. Pretty confusing.  I think it's related to the parsing of the last command. I'll try to have a look at it on the train to work.

**Comment by dflock** [comment]
This also appears to be fixed with latest master!
