### ISSUE TITLE
Missing settings.default?

### ISSUE THREAD

**Issue by jlyman** [brujoand/sbp#39]
I checked out the project from `master` and ran the install script in the root folder, and while completing the second two steps, it doesn't find the `settings.default` file and therefore doesn't copy it over to `~/.sbp`. SBP doesn't seem to be running without it (I just get my normal prompt).

Is there something that I'm missing here? (macOS 10.12.1)

**Comment by brujoand** [comment]
Oops, no it seems I forgot to update the install script after my last refactor. Sorry about that, I should add some test for it as well. 

Line 8 of the installer should've copied ${sbp_path}/helpers/defaults.bash into ~/.config/sbp/sbp.conf if iirc. I'm on my phone so I'll have to check in the morning and patch it. But changing that one line should/might fix it.

**Comment by jlyman** [comment]
Ah gotchya, that makes sense. Thanks!

**Comment by brujoand** [comment]
If you want to try again now it should be fixed.

**Comment by jlyman** [comment]
That worked! 

I still wasn't having anything show up until I realized that everything was going into .bashrc, instead of my .bash_profile. Copying the last two lines for the `sbp_path` into my .bash_profile started it right up. Now I just have to figure out why the segment separator characters aren't showing up, despite having the Powerline patched fonts installed... :)

Thanks for the fix.

**Comment by jlyman** [comment]
Oh, and nm on the font. I'm using iTerm and had changed the Font setting but forgot to also change the Non-ASCII Font setting. All good! :)
