### ISSUE TITLE
Root shows in the path only when the current directory is root itself

### ISSUE THREAD

**Issue by qub1750ul** [brujoand/sbp#40]
![git_root_bug](https://cloud.githubusercontent.com/assets/20952171/26832508/010d7e24-4ad0-11e7-8b9b-1c14af076300.png)

**Comment by brujoand** [comment]
I made a quickfix for this #42. Seems fixed here atleast. Can you confirm?

**Comment by qub1750ul** [comment]
Yes.
![schermata del 2017-07-22 11-27-03](https://user-images.githubusercontent.com/20952171/28490011-c2a43a7c-6ed0-11e7-8ba4-32bbdc99b514.png)
