### ISSUE TITLE
segment_line_two works bad if segments_right isn't set

### ISSUE THREAD

**Issue by qub1750ul** [brujoand/sbp#44]
There are the screenshots of my tests:
- Configs with normal behavior
![schermata del 2017-07-22 13-08-39](https://user-images.githubusercontent.com/20952171/28490668-131278a2-6ee0-11e7-9bbe-adea43ee9099.png)
![schermata del 2017-07-22 13-10-40](https://user-images.githubusercontent.com/20952171/28490676-27bcb394-6ee0-11e7-975d-8611cbafcdcd.png)
- Configs with bad behavior
![schermata del 2017-07-22 13-09-30](https://user-images.githubusercontent.com/20952171/28490670-1a6f1a2e-6ee0-11e7-9b2a-af78080a9146.png)
![schermata del 2017-07-22 13-10-08](https://user-images.githubusercontent.com/20952171/28490674-21d14468-6ee0-11e7-84f2-d16e3988ef04.png)

**Comment by brujoand** [comment]
Tried playing with this a bit. Managed to get it almost right by making the prompt generator be aware that the right prompt list is empty. Feel free to try to tweak that an create a PR. Specifically this line needs to be skipped it there is nothing in the right prompt --> https://github.com/brujoand/sbp/blob/master/helpers/prompt.bash#L80
