### ISSUE TITLE
Transparent filler

### ISSUE THREAD

**Issue by Phidelux** [brujoand/sbp#6]
Currently trying to implement a toggle to make the filler transparent. However I am not able to change the background of the arrow of the previous and next element arrow, as they seem to accept only the color code not the complete escape sequence. Do you have an idea how to fix this without rewriting the color function?

**Comment by brujoand** [comment]
Ah, my terminal background is dead black so I've actually never noticed this. My initial intention was for the filler to be blank. I'm trying to figure something out now, but it feels like the color.bash should handle this better.
