### ISSUE TITLE
settings_git_max_length doesn't seem to work since #64

### ISSUE THREAD

**Issue by dflock** [brujoand/sbp#72]
**Describe the bug**
Whatever I set `settings_git_max_length` to, I always get a 10 char long branch name in the git segment, if my branch name is >30 chars. This appears to be caused by this code:

```sh
if [[ $(( ${#git_head} + ${#git_state} )) -gt "$settings_git_max_length" ]]; then
  git_head="${git_head:0:10}.."
fi
```

If I print out `$settings_git_max_length` inside `git.bash`, it always seems to be set to `30` - this is also the case it I print out `$4` right at the top. This is true whatever I set it to in my `~/.config/sbp/settings.conf` file.

**To Reproduce**
1. Install sbp as per readme
2. Set `$settings_git_max_length` in your `~/.config/sbp/settings.conf` file
3. Go to a git repo folder with a branch nae longer that 30 chars.

**Expected behavior**
- I would expect the configured value to make it into the segment, not to have it reset to 30.
- I would also expect the length of the truncated branch name to be related to settings_git_max_length, not always be 10.

I've had a poke around but I can't see why this is happening.

Also, why truncate the branch to 10 chars? Shouldn't it truncate the branch to something like (pseudocode): `$settings_git_max_length - len(git_state + settings_git_icon + upstream_status)`, so maybe something like this:

```sh
if [[ $(( ${#git_head} + ${#git_state} )) -gt "$settings_git_max_length" ]]; then
  # git_head="${git_head:0:10}.."
  len=$(( $settings_git_max_length - ( ${#git_state} + ${#settings_git_icon} + ${#upstream_status} ) ))
  git_head="${git_head:0:$len}.."
fi
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04.3 LTS x86_64 
 - Terminal: kitty 0.15.0

**Comment by brujoand** [comment]
Thanks for bringing this up. I actually forgot about this when adding the "max size pr segment" feature which is $4. So the ´$settings_git_max_length´ gets overwritten by ´$COLUMNS/${#segments}´. This was a hack to just make it work but should be fixed to work as expected.

**Comment by dflock** [comment]
I've modified my local checkout of `segments/git.bash` to look like this as a quick fix:

```sh
if [[ $(( ${#git_head} + ${#git_state} )) -gt "$settings_git_max_length" ]]; then
  # git_head="${git_head:0:10}.."
  len=$(( $settings_git_max_length - ( ${#git_state} + ${#settings_git_icon} + ${#upstream_status} ) + 4 ))
  git_head="${git_head:0:$len}.."
fi
```

**Comment by dflock** [comment]
I've pulled up to the latest master now, so I have #73, thanks.

How can I control the `$segment_max_length` for a given segment (in this case just git) - without modifying the segments `.bash` file?

Essentially, I want the git segment to be longer, because sometimes my branch names are pretty long. I can edit `sbp/segments/git.bash` and hardcode a longer value:

```bash
#! /usr/bin/env bash

segment_direction=$3
segment_max_length=$4

segment_max_length=250
```

but it there a better way to do this?

**Comment by brujoand** [comment]
Hm, good question. I'm doing a pretty substantial rewrite right now of how these types of settings are passed into the segment generation. What if every segment gets a a parameter 'segment_max_length' which is basically just 'available space / number of segments' and this can be overridden by setting a max length for the specific segment?

**Comment by dflock** [comment]
That sounds reasonable.

Something else to consider, is that I have the git segment as the last segment on the left, like this:

![image](https://user-images.githubusercontent.com/47756/86440613-a3235a80-bcbf-11ea-97e7-bdecc3196c98.png)

The first prompt is before and the second is after modifying `git.bash` a hard-coding `segment_max_length=250`:

![image](https://user-images.githubusercontent.com/47756/86440735-d6fe8000-bcbf-11ea-9864-f44e50112109.png)

So, that window is very wide and there's loads of room for that last segment to expand into. In my case here, that's what I want - I want the last segment on the left to flex into the empty space and take up as much space as it needs. I don't really want to have to set a specific value for it - I just want it to grow to fit the branch name.

**Comment by brujoand** [comment]
Right, so I guess one way would be to allow a setting that skips any shortening. Overriding the max length to '-1' sounds like fair approach, what do you think?

**Comment by dflock** [comment]
Yeah, that sounds reasonable to me!

**Comment by brujoand** [comment]
Btw, does this work as expected now with the latest changes?

**Comment by dflock** [comment]
Well, it works if I add this to the top of `git.bash`:

```
  local max_length=-1
```

Not sure how to set this, for the git segment, in the config?

**Comment by brujoand** [comment]
Yeah, I’m on mobile right now but iirc “SEGMENTS_GIT_MAX_LENGTH=-1” in the config should give the same result. That was the intention atleast.

**Comment by dflock** [comment]
That works, thanks!

**Comment by brujoand** [comment]
Sweet!
