### ISSUE TITLE
Way to only show git branch instead of other info. (slow)

### ISSUE THREAD

**Issue by thepenguinthatwants** [brujoand/sbp#76]
At first need to say thanks for giving such a beautiful bash prompt for us to use.

Just that the git module sometimes slows down my bash prompt a lot especially when having a huge git repo. Is there a way to make it only check which git branch instead of going through all the other checks?

**Comment by brujoand** [comment]
Hey, I seem to have lost notifications for issues so I didn’t see this until now. But you’re quite right. The git integration is hard to get right especially with large repos. 


I’m in the process of rewriting some of the segments to increase speed these days, and a feature to disable anything but branch sounds like a good addition 👍

**Comment by brujoand** [comment]
Hey, I've been looking at this a bit, using https://github.com/torvalds/linux as a test repo. With the current implementation the git segment takes 447ms, and now that I've added the option to set ´SEGMENTS_GIT_BRANCH_ONLY=true´ we're down to 16ms. With this approach one could put a check in the config for the current path, and if we are in one of the big repos, set this variable to true. Anyway, I've added this on the #77 PR which should be merged in the coming days.

**Comment by thepenguinthatwants** [comment]
OMG cool. Thanks for telling.
I've being using this without git module and having the ability to use it again is def great!

**Comment by brujoand** [comment]
Np! :)

**Comment by thepenguinthatwants** [comment]
How do u apply it?
I tried sbp edit config, but cant understand which one is the setting to make it only show git branch?
