### ISSUE TITLE
Powerline layout In Termux showing wrong charaterset

### ISSUE THREAD

**Issue by akoerner** [brujoand/sbp#85]
**Describe the bug
Charaters in the powerline layout being displayed are not intended charaters.  

**To Reproduce**
1. Under android in termux clone the repository
2. Run the bin/install script
3. set the layout to [powerline](url)

**Expected behavior**
should work without installing fonts or external dependencies.

**Screenshots**
[https://imgur.com/a/cfu0kTr ](https://imgur.com/a/cfu0kTr)

**Environment (please complete the following information):**
 - OS: [Android 10]
 - Terminal [Termux]
 - Version []

➜ bash --version
GNU bash, version 5.0.11(1)-release (aarch64-unknown-linux-android)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Additional context**

~  sbp  bin   master  last: 0m 0s  echo $LANG
en_US.UTF-8

**Comment by brujoand** [comment]
> should work without installing fonts or external dependencies.
The powerline symbols can't work without patched fonts, except if the terminal knows how to draw them like Kitty for instance. From the screenshot it looks like you are using a font which already has values for the characters used by powerline, which font is this? 

I'd try something like this https://github.com/adi1090x/termux-style just to verify. It could be that the font you are using do support the powerline symbols but have different values for them, in that case you'd need to change the SBP config.

**Comment by spamegg1** [comment]
@akoerner https://github.com/powerline/fonts
Might want to try with some of the fonts from here. I had the same problem on bash/gnome-terminal and this fixed it.

**Comment by SuperSandro2000** [comment]
I don't use any patched font but just installed the [nerd fonts symbols font file.
](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-1000-em%20Nerd%20Font%20Complete.ttf)
![](https://i.imgur.com/qUkxbdi.jpg)

**Comment by brujoand** [comment]
Aye, so basically you'll either need fonts that support powerline glyphs, or a terminal that can draw the glyphs manually if you want to use the powerline layout unfortunatly.
