### ISSUE TITLE
Better document variables for segment colors

### ISSUE THREAD

**Issue by SuperSandro2000** [brujoand/sbp#89]
**Is your feature request related to a problem? Please describe.**
It took me over 15 minutes to find the right variable to change the exit code segment. ``SEGMENTS_EXIT_CODE_COLOR_PRIMARY_HIGHLIGHT``

**Describe the solution you'd like**
List all of them in the sample config.

**Describe alternatives you've considered**
Add a command which lists all of them or the scheme how they are generated.

**Additional context**
I don't know all variables or how the schema they follow so I can't do a PR.

**Comment by brujoand** [comment]
Yeah, these variables were recently moved out of the segment scripts. That cleaned up a lot of overreaching code, but now the color variables are a bit like magic, and hidden from the segments. I'm not sure if theres a better solution than just documentation here though as all the color variables follow the same naming pattern.

**Comment by brujoand** [comment]
I've added 'sbp list config' now which lists all active settings including colors.

**Comment by SuperSandro2000** [comment]
One setting is empty for me and I don't think I unset it.
``` 
SEGMENTS_PROMPT_READY_COLOR_PRIMARY           
` ``

**Comment by brujoand** [comment]
Yeah, it's not set by default, but not for good reason. It started out as a way of having it not be powerline themed. Basically this let's it not have a background color. But this should be handled in the layout instead.
