### ISSUE TITLE
Having trouble creating a new segment - causes the filler to be the wrong size?

### ISSUE THREAD

**Issue by dflock** [brujoand/sbp#9]
I've created a new segment to show the return code of the last command. This is the segments code, saved in `segments/rc.bash`:

```bash
### Defaults
_sbp_rc_bg=${_sbp_rc_bg-:$_sbp_color_red}
_sbp_rc_fg=${_sbp_rc_fg-:$_sbp_color_white}

function _sbp_generate_rc_segment {
  local command_color command_value
  if [[ "$_sbp_current_exec_result" -ne 0 && "$_sbp_current_exec_result" -ne 130 ]]; then
    command_color=$(print_color_escapes "$_sbp_rc_fg" "$_sbp_rc_bg")
    command_value="${command_color}${_sbp_current_exec_result}"

    _sbp_segment_new_color="$_sbp_rc_bg"
    _sbp_segment_new_length="$(( ${#command_value} + 2 ))"
    _sbp_segment_new_value="${command_color} ${command_value} "
    _sbp_segment_new_create
  fi
}
```
I've added this into `helpers/imports.bash` and it works when I use it - but it messes up the filler; it does this whether if I place it on the right or the left hand side.

Here's the prompt with the `rc` segment enabled. First, with a return code of zero, so it's not shown, then with a return code of 127, so it shows the segment:

![image](https://cloud.githubusercontent.com/assets/47756/13727564/1f78e506-e8ac-11e5-9980-e1810dc0ea3a.png)

Here's the actual text of that screenshot, copied and pasted, in case the char counts are helpful:

```
duncan  ~  bin  sbp   show_rc_in_command ?*                                               last: 0m 0s  23:41:13 
 ➜ sdfsd
sdfsd: command not found

 duncan  ~  bin  sbp   show_rc_in_command ?*  127              last: 0m 0s  23:41:16 
 ➜ 
```

**Comment by Phidelux** [comment]
Maybe related to issue #8 "Filler width calculation ".

**Comment by brujoand** [comment]
Yeah there is definitely something weird about the calculated size. I've been trying to wrap my head around it but haven't really figured it out. If anyone has enough regex skills to filter out all escape characters from the left and right prompt, that would probably be a lot better than manually keeping track.

**Comment by Phidelux** [comment]
You can remove colorcodes with the following sed command:

sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"

**Comment by dflock** [comment]
I've pulled up to the latest master and been a bit more careful about setting `_sbp_segment_new_length` correctly and this seems to be fixed - at least for the segments I'm creating at the moment.
