### ISSUE TITLE
conda env segment

### ISSUE THREAD

**Issue by jbuencuerpo** [brujoand/sbp#93]
Really cool tool. But I cannot use it (I guess every conda user) unless it has conda env support, please extend support for conda environments.I guess it should be easy to add, as you have a python_env support. 

Thanks in any case.

**Comment by brujoand** [comment]
Hey, I haven't actually used conda before, but a quick google search told me that the current env is stored in '$CONDA_DEFAULT_ENV'. So I've added a super simple segment that displays that value if set. If you update to the latest version you should be able to add 'conda' as a segment.

**Comment by jbuencuerpo** [comment]
Perfect!  I tried the add_conda_env and it works nicely. 
Thank you very much, I am closing this.
